[package]
name = "compiler-book"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = "0.9.3"
indoc = "2.0.4"
logos = "0.13.0"
once_cell = "1.19.0"
pretty_assertions = "1.4.0"
thiserror = "1.0.56"
